project_name: rhcsa-tui
version: 2
before:
  hooks:
    - go mod download
builds:
  - id: rhcsa-tui
    main: ./cmd/rhcsa-tui/main.go
    binary: rhcsa-tui
    env:
      - CGO_ENABLED=0
    goos:
      - windows
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
archives:
  - id: default
checksum:
  algorithm: sha256
release:
  github:
    owner: "{{ .Env.GH_OWNER }}"
    name: "{{ .Env.GH_REPO }}"
  draft: true
  prerelease: auto
