@{
RootModule = 'VMControl.psm1'
ModuleVersion = '0.1.0'
GUID = 'd4e5f6a7-b8c9-4d0e-8f1a-2b3c4d5e6f7a'
Author = 'Firas Ben Nacib'
CompanyName = 'RHCSA Simulator'
Copyright = '(c) Firas Ben Nacib. All rights reserved.'
Description = 'VM control, Vagrant orchestration, and VirtualBox snapshot management.'
PowerShellVersion = '5.1'
FunctionsToExport = @(
    'Clear-LabCheckScriptState'
    'Confirm-VagrantGuestProvisionReadiness'
    'ConvertFrom-VirtualBoxState'
    'ConvertTo-BashSingleQuotedString'
    'ConvertTo-PowerShellSingleQuotedString'
    'Get-BaselineStatus'
    'Get-LabCheckProvisionerName'
    'Get-LabCheckScriptPath'
    'Get-LabMachineIdList'
    'Get-LabVBoxVmCandidate'
    'Get-OptionalVagrantMachineId'
    'Get-RhcsaOfflineIsoPath'
    'Get-RhcsaPreflightStatus'
    'Get-ScenarioStatus'
    'Get-SshExecutablePath'
    'Get-VBoxHardDiskCatalog'
    'Get-VBoxMachineFolder'
    'Get-VBoxMachineState'
    'Get-VBoxSnapshotCatalog'
    'Get-VBoxVmCatalog'
    'Get-VagrantMachineId'
    'Get-VagrantMachineStatus'
    'Get-VirtualBoxMachineStatusFallback'
    'Get-VmDirectSshLaunchSpec'
    'Get-VmSshConfig'
    'Get-VmSshConnectionInfo'
    'Initialize-ClientLabDiskSet'
    'Initialize-VBoxLabDiskFile'
    'Import-RhcsaOfflineIso'
    'Invoke-BaseSnapshotInitialization'
    'Invoke-BaseSnapshotRestore'
    'Invoke-ClientRecoveryConsole'
    'Invoke-LabExerciseCheck'
    'Invoke-LabHypervisorLockCleanup'
    'Invoke-LiteralPathRemovalWithRetry'
    'Invoke-OrphanVmFolderCleanup'
    'Invoke-ScenarioProvisioning'
    'Invoke-SshWithVmConfig'
    'Invoke-VBoxHardDiskCleanup'
    'Invoke-VBoxSnapshotCommand'
    'Invoke-VBoxVmRemoval'
    'Invoke-VagrantCommand'
    'Invoke-VagrantMachineStep'
    'Invoke-VagrantVmShellCommandCapture'
    'New-SshSessionKeyFile'
    'Open-VmSshSession'
    'Remove-LabEnvironment'
    'Remove-OrphanLabDiskSet'
    'Repair-BaselineSnapshotIfNeeded'
    'Reset-ScenarioRun'
    'Resume-LabEnvironment'
    'Set-ForceHostCleanup'
    'Start-BaselineSession'
    'Start-ScenarioRun'
    'Stop-VBoxMachineForSnapshot'
    'Suspend-LabEnvironment'
    'Test-BaseSnapshot'
    'Test-BaselineOfflineRepoHealth'
    'Test-ForceHostCleanupEnabled'
    'Test-GuestBaselineReady'
    'Test-IsAssertiveExerciseCheck'
    'Test-LabHypervisorBusy'
    'Test-LocalLabArtifactsPresent'
    'Test-ProcessCommandLineMatchesLab'
    'Test-SshBannerReady'
    'Test-VBoxVmRegistration'
    'Test-VagrantClientBusy'
    'Test-VagrantSshConnectivity'
    'Wait-LabHypervisorQuiescence'
    'Wait-VBoxMachineReady'
    'Wait-VBoxMachineState'
    'Wait-VagrantClientQuiescence'
    'Wait-VagrantGuestSshReady'
    'Write-LabCheckScript'
)
CmdletsToExport = @()
VariablesToExport = @()
AliasesToExport = @()
}
