@{
RootModule = 'Rhcsa.Ui.psm1'
ModuleVersion = '0.1.0'
GUID = 'c5d6e7f8-a9b0-4c1d-d2e3-f4a5b6c7d8e9'
Author = 'Firas Ben Nacib'
CompanyName = 'RHCSA Simulator'
Copyright = '(c) Firas Ben Nacib. All rights reserved.'
Description = 'Terminal UI formatting module for the RHCSA CLI.'
PowerShellVersion = '5.1'
FunctionsToExport = @(
    'Format-BaselineStartOutput'
    'Format-BaselineAlreadyRunningOutput'
    'Format-DashboardOutput'
    'Format-DestroyOutput'
    'Format-ExerciseCheckOutput'
    'Format-PaddedCell'
    'Format-RepoHealthOutput'
    'Format-ScenarioCatalogOutput'
    'Format-ScenarioCatalogTable'
    'Format-ScenarioResetOutput'
    'Format-ScenarioStartOutput'
    'Format-ScenarioStatusOutput'
    'Format-LeaveOutput'
    'Format-ResumeOutput'
    'Format-StyledText'
    'Format-UiCommandLine'
    'Format-UiKeyValue'
    'Format-UiLabelValue'
    'Format-UiPanel'
    'Format-VmSshOutput'
    'Format-VmStatusOutput'
    'Get-ExerciseCheckSummaryLabel'
    'Get-MaxCellWidth'
    'Get-RhcsaAsciiBanner'
    'Get-UiHeading'
    'Get-UiStyleCode'
    'Test-UiColorSupport'
)
CmdletsToExport = @()
VariablesToExport = @()
AliasesToExport = @()
}
